<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Italbytz.Meal.Abstractions\Italbytz.Meal.Abstractions.csproj" />
    <ProjectReference Include="..\Italbytz.Meal.STWPB.Client\Italbytz.Meal.STWPB.Client.csproj" />
    <PackageReference Include="Italbytz.Common.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Italbytz.Meal.STWPB</PackageId>
    <Description>STWPB-backed meal services and mapping helpers.</Description>
  </PropertyGroup>

</Project>
