<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Italbytz.Meal.STWPB/Italbytz.Meal.STWPB.csproj" />
    <Compile Include="../Shared/StwpbSampleSnapshot.cs" Link="Shared/StwpbSampleSnapshot.cs" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>