<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <ItemGroup>
    <ProjectReference Include="../../src/Italbytz.Meal.Abstractions/Italbytz.Meal.Abstractions.csproj" />
    <Compile Include="../Shared/StwpbSampleSnapshot.cs" Link="Shared/StwpbSampleSnapshot.cs" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>